import Head from "next/head";
import Appbar from "../components/Appbar";
import CustomTabs from "../components/CustomTabs";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, LinearProgress } from "@mui/material";
import Item from "../components/Task/Item";
import List from "../components/Task/Listitem";
import TodoList from "../components/Task/TodoList";
import App from "../components/Modal/ProfileModal";
import AddEdit from "../components/Modal/AddEditModal";
import Profile from "../components/Modal/ProfileModal";
import Report from "../components/Modal/ReportModal";
import Settings from "../components/Modal/SettingsModal";
import Subscriptions from "../components/Modal/SubscriptionModal";
import AddEditModal from "../components/Modal/AddEditModal";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar />
        <LinearProgress variant="determinate" />
        <div className={styles.main}>
          <div className={styles.centerBox}>
            <div className={styles.centerBoxItems}>
              <CustomTabs />
            </div>
            <div className={styles.centerBoxItems}>
              <Button
                variant="contained"
                sx={{ bgcolor: "#fff", color: "rgb(217, 85, 80)" }}
              >
                Start
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.taskItem}>
        <List />
      </div>
    </>
  );
}
